version: 0.2.1.{build}
os: Visual Studio 2017

# Only focus on the master branch
branches:
  only:
  - master
  - main   # If/when the master branch becomes 'main'

install:

build_script:
- cmd: dotnet --info
- ps: .\build.ps1

test: off

artifacts:
- path: artifacts/zip/*.zip
- path: artifacts/nuget/*.nupkg